#+title: Tips and tricks for this configuration

* Window management
- Press alt + arrows to move between windows. You can't do that in org-mode so use ~C-x o~ there.
- ~C-c C-r~ will transpose windows

* Git
** Magit Status buffer
- Press ~j~ and another letter to jump to any of the sections

** Git link
- ~C-c G H~ will take you to the repository home page. Useful when you push a commit and want to open a pull request

** Working with multiple emails
When working on a business computer you often omit your email from the global git configuration in
order to configure it on per-repository basis. You can customize ~my/emails~ in your site file like
this:

#+BEGIN_SRC emacs-lisp
(setq my/emails '("me@home.com" "me@work.com"))
#+END_SRC

Then run ~my/set-git-email~ to select one of these emails.

* Snippets
- ~C-M-/~ will list the available snippets with their respective keys
- ~M-/~ will expand a snippet key

* Language specific
** Python
**** Virtual environments
Once you have a virtual environment, use ~C-c p E~ to define the variable ~pyvenv-activate~ for the
current project. Store the path of the virtual environment inside this variable. Remember to quote
that path with double quotation marks.

**** Pylint
If you install pylint in your virtual environment then you should get automatic checking for your
project. Press ~C-! v~ when visiting a Python file to make sure that the pylint executable is picked
from the correct virtual environment.

**** Python language server
You can install ~python-language-server~ in your virtual environment using pip. It's recommended to
install ~python-language-server[pylint]~ in order to an integration with pylint. Once that is set up
the modeline should indicate that the Python Language Server is running by showing ~LSP[pyls:pid]~.

**** Auto formatting
This configuration supports automatic Python formatting on save. Since there's no consensus about a
Python formatting tool, or whether to use such at all, this feature is turned off and can be enabled
on project basis.

Two buffer local variables were created for this - ~my/python-isort-on-save~ which runs [[https://github.com/timothycrosley/isort/][isort]] and
~my/python-black-on-save~ which runs [[https://github.com/ambv/black][black]]

These variables are local buffer and are nil by default. They can be set for a given project by
using dir-local variables, just like ~pyvenv-activate~. Use ~C-c p E~ to set them.
