#+title: Tips and tricks for this configuration

* Customization
** Custom file
The easiest method for customizing settings is via the custom file, which is located at
~/.emacs.d/custom.el~. Press ~M-x customize-group~ in order to find out which customization options
are available for a given package. There is also a customization group for this configuration called
~my/customization~. Once you make your changes in the UI you can save them just like any other
buffer. Note that the custom file is placed within the configuration repository and is
untracked. Meaning that changes will not persist across computers and the file will be purge when
running ~git clean~. If you wish for more persist customization see [[Customization directory]].

** Customization directory
See the [[file:README.md][README]] file

** Buffer local variables
Some variables can be customized per buffer bases. These is done using [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][Dir locals]]. Press ~C-c p E~
to customize these variables. The syntax on this file might seem crypting, but just think of it as a
dict mapping between a major mode to a lists of tuples.

* Navigation
** Inside a buffer
- ~S-s~ activates [[https://github.com/abo-abo/avy][Avy]] which allows you to navigate by typing words
- ~C-f~ and ~C-b~ are similar to Vim's ~f~ and ~b~. See [[https://github.com/lewang/jump-char][jump-char]].

** Switch Windows
- Press alt + arrows to move between windows. You can't do that in org-mode so use ~C-x o~ there.
- ~C-c C-r~ will transpose windows

* Git
** Git timemachine
- Press ~M-<f9>~ to activate a time machine mode when visiting a file. Press ~?~ inside this mode to
  see the key bindings.

** Magit Status buffer
- Press ~j~ and another letter to jump to any of the sections

** Git link
- ~C-c G H~ will take you to the repository home page. Useful when you push a commit and want to open a pull request

** Working with multiple emails
When working on a business computer you often omit your email from the global git configuration in
order to configure it on per-project basis. You can customize ~my/emails~ in your site file like
this:

#+BEGIN_SRC emacs-lisp
(setq my/emails '("me@home.com" "me@work.com"))
#+END_SRC

Then run ~my/set-git-email~ to select one of these emails.

* Snippets
- ~C-M-/~ will list the available snippets with their respective keys
- ~M-/~ will expand a snippet key
- ~C-S-w~ defines a temporary snippet from the current line and ~C-S-y~ applies it. See [[https://github.com/abo-abo/auto-yasnippet/blob/master/README.md][auto-yasnippet]].

* Language specific
** Python
**** Virtual environments
Once you have a virtual environment, use ~C-c p E~ to define the variable ~pyvenv-activate~ for the
current project. Store the path of the virtual environment inside this variable. Remember to quote
that path with double quotation marks.

**** Pylint
If you install pylint in your virtual environment then you should get automatic checking for your
project. Press ~C-! v~ when visiting a Python file to make sure that the pylint executable is picked
from the correct virtual environment.

**** Python language server
You can install ~python-language-server~ in your virtual environment using pip. It's recommended to
install ~python-language-server[pylint]~ in order to get an integration with pylint. Once that is
set up the modeline should indicate that the Python Language Server is running by showing
~LSP[pyls:pid]~.

**** Auto formatting
This configuration supports automatic Python formatting on save. Since there's no consensus about a
Python formatting tool, or whether to use such at all, this feature is turned off and can be enabled
on project basis.

Two buffer local variables were created for this - ~my/python-isort-on-save~ which runs [[https://github.com/timothycrosley/isort/][isort]] and
~my/python-black-on-save~ which runs [[https://github.com/ambv/black][black]].

These variables are local buffer and are nil by default. They can be set for a given project by
using dir-local variables, just like ~pyvenv-activate~. See [[Buffer local variables]].
* Org mode
- ~S-f10~ is a global key that uses counsel to display the headers of every open org buffer
