name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Emacs
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install emacs26-nox
    - name: Byte compile files
      run: git ls-files '*.el' ':!:.*' -z | xargs -0 -I {} emacs -Q --batch -l .ci.el --eval '(byte-compile-file "{}")'
